"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { beginTotpEnrollment, removeTotp, verifyTotp } from "@/lib/auth/actions";

export function MfaPanel({ factorId, verified }: { factorId: string | null; verified: boolean }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [enrollment, setEnrollment] = useState<{ factorId: string; qrCode: string; secret: string } | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState("");

  function enroll() {
    setError("");
    startTransition(async () => {
      const result = await beginTotpEnrollment();
      if (result.ok) setEnrollment(result.data);
      else setError(result.message);
    });
  }

  function verify(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    startTransition(async () => {
      const result = await verifyTotp(factorId ?? enrollment?.factorId ?? "", code);
      if (result.ok) {
        router.push("/dashboard");
        router.refresh();
      } else setError(result.message);
    });
  }

  function remove() {
    if (!factorId || !window.confirm("Remover a autenticação em duas etapas desta conta?")) return;
    setError("");
    startTransition(async () => {
      const result = await removeTotp(factorId);
      if (result.ok) router.refresh();
      else setError(result.message);
    });
  }

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Autenticação em duas etapas</CardTitle>
        <CardDescription>
          {verified ? "Seu autenticador está ativo nesta sessão." : factorId ? "Digite o código do aplicativo autenticador para continuar." : "Proteja sua conta com um aplicativo autenticador."}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {!factorId && !enrollment && <Button onClick={enroll} disabled={pending}>Ativar autenticador</Button>}
        {enrollment && (
          <div className="space-y-3">
            {/* QR code is generated by Supabase Auth and shown only to the account owner. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={enrollment.qrCode} alt="Código QR para configurar o autenticador" className="size-48 bg-white p-2" />
            <p className="text-sm">Ou digite esta chave no aplicativo: <code className="break-all">{enrollment.secret}</code></p>
          </div>
        )}
        {verified && factorId && <Button variant="outline" onClick={remove} disabled={pending}>Remover autenticador</Button>}
        {!verified && (factorId || enrollment) && (
          <form onSubmit={verify} className="space-y-3">
            <label htmlFor="totp-code" className="text-sm font-medium">Código de 6 dígitos</label>
            <Input id="totp-code" value={code} onChange={(event) => setCode(event.target.value.trim())} inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" required />
            <Button type="submit" disabled={pending}>{pending ? "Validando..." : "Confirmar código"}</Button>
          </form>
        )}
        {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
      </CardContent>
    </Card>
  );
}
