#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-.env.local}"

banner "AgendFined security release"

stage "Supabase: server configuration"
say "Configure the local server environment without exposing credentials in the terminal log."
open_url "https://supabase.com/dashboard/projects"
step "Open the project used by this checkout and confirm the security migration is applied."
step "In Project Settings → API, copy the project URL and publishable key."
ask NEXT_PUBLIC_SUPABASE_URL "Project URL:"
ask NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Publishable key:"
step "Copy the Secret key (sb_secret_..., formerly service_role) only from the server-side secret area. Never paste it into chat or a NEXT_PUBLIC variable."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Secret key (sb_secret_...):"
[[ -z "$NEXT_PUBLIC_SUPABASE_URL" ]] || write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
[[ -z "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" ]] || write_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
[[ -z "$SUPABASE_SERVICE_ROLE_KEY" ]] || write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
step "In the Edge Function environment, configure the same server-only keys required by the reminder job."
pause "After saving the Supabase secrets, press Enter"

stage "Mercado Pago: checkout and alerts"
say "Configure the server-authoritative price, webhook verification, and billing alert."
open_url "https://www.mercadopago.com/developers/panel"
step "Open the production application (or the test application for local work)."
step "Copy the access token from the server credentials area."
ask_secret MERCADO_PAGO_ACCESS_TOKEN "Access token:"
step "In Webhooks, configure /api/webhooks/mercadopago for subscription_preapproval and copy the signing secret."
ask_secret MERCADO_PAGO_WEBHOOK_SECRET "Webhook secret:"
ask MERCADO_PAGO_NOTIFICATION_URL "Public webhook URL:"
ask MERCADO_PAGO_PRO_AMOUNT_CENTS "PRO price in cents [1900]:"
[[ -z "$MERCADO_PAGO_ACCESS_TOKEN" ]] || write_env MERCADO_PAGO_ACCESS_TOKEN "$MERCADO_PAGO_ACCESS_TOKEN"
[[ -z "$MERCADO_PAGO_WEBHOOK_SECRET" ]] || write_env MERCADO_PAGO_WEBHOOK_SECRET "$MERCADO_PAGO_WEBHOOK_SECRET"
[[ -z "$MERCADO_PAGO_NOTIFICATION_URL" ]] || write_env MERCADO_PAGO_NOTIFICATION_URL "$MERCADO_PAGO_NOTIFICATION_URL"
[[ -z "$MERCADO_PAGO_PRO_AMOUNT_CENTS" ]] || write_env MERCADO_PAGO_PRO_AMOUNT_CENTS "$MERCADO_PAGO_PRO_AMOUNT_CENTS"
step "Configure the provider's billing/spend notifications for the account and webhook failures."
pause "After saving Mercado Pago settings, press Enter"

stage "Resend: email delivery"
say "Configure booking confirmation delivery and the reminder function secret."
open_url "https://resend.com/api-keys"
step "Create or copy a server-only API key with the minimum scope needed to send booking emails."
ask_secret RESEND_API_KEY "Resend API key:"
ask RESEND_FROM_EMAIL "Verified sender email:"
ask_secret REMINDER_CRON_SECRET "Reminder dispatch shared secret:"
[[ -z "$RESEND_API_KEY" ]] || write_env RESEND_API_KEY "$RESEND_API_KEY"
[[ -z "$RESEND_FROM_EMAIL" ]] || write_env RESEND_FROM_EMAIL "$RESEND_FROM_EMAIL"
[[ -z "$REMINDER_CRON_SECRET" ]] || write_env REMINDER_CRON_SECRET "$REMINDER_CRON_SECRET"
step "Set the same reminder secret in the Supabase Edge Function and scheduler configuration."
pause "After saving email settings, press Enter"

stage "TypeSafe: AI budget"
say "Enable optional AI features with a server-only key and provider billing limits."
step "Open the TypeSafe provider dashboard for this account and create/copy a server API key."
ask_secret TYPESAFE_API_KEY "TypeSafe API key:"
[[ -z "$TYPESAFE_API_KEY" ]] || write_env TYPESAFE_API_KEY "$TYPESAFE_API_KEY"
step "Configure the provider's billing alert and a hard spending cap if the account supports it."
pause "After saving the TypeSafe settings, press Enter"

stage "Secret rotation"
say "Revoke credentials that may have appeared in old Git history and issue fresh values."
step "Rotate any Supabase service-role, Mercado Pago, Resend, TypeSafe, webhook, or scheduler secret that was ever committed."
step "Reset any shared demo or integration account that used an old test password."
step "Do not rewrite Git history unless the repository owner explicitly approves that destructive operation."
pause "After completing secret rotation, press Enter"

stage "Deployment: production variables"
say "Copy the server-only values from this local file into the hosting provider's encrypted environment settings."
open_url "https://vercel.com/dashboard"
step "Select the production project and add the variables from .env.example for Production."
step "Never add SUPABASE_SERVICE_ROLE_KEY, TYPESAFE_API_KEY, access tokens, or webhook secrets as NEXT_PUBLIC variables."
step "Set APP_URL and MERCADO_PAGO_NOTIFICATION_URL to the final HTTPS domain."
step "Redeploy after saving variables; do not commit .env.local."
pause "After the production redeploy, press Enter"

stage "Final verification"
step "Run the local checks against the configured environment."
npx vitest run --project unit
npm run lint
npm run typecheck
npm run build
step "Run the Node 22 integration suite against the linked Supabase project when the environment is available."
note "Command: npm run test:integration"
note "The wizard does not execute integration tests automatically because they can mutate the linked project."
# ──────────────────────────────────────────────────────────────────────────

finish
