-- Backend security/concurrency hardening generated by the Spec Kit plan
-- `001-backend-security-concurrency-hardening`.
--
-- This migration is intentionally additive/forward-only. It removes the
-- anonymous base-table catalog policies only after installing explicit public
-- projections, and it keeps the existing booking RPC signatures compatible.

-- ---------------------------------------------------------------------------
-- Public catalog: expose an allowlisted projection, never `select *` from the
-- businesses/services tables through PostgREST.
-- ---------------------------------------------------------------------------
drop policy if exists businesses_select_public on public.businesses;
drop policy if exists services_select_public on public.services;

create or replace function public.get_public_business(p_slug text)
returns table (
  id uuid,
  name text,
  slug text,
  description text
)
language sql
security definer
set search_path = ''
as $$
  select b.id, b.name, b.slug, b.description
  from public.businesses b
  where b.slug = p_slug
    and b.is_active = true
$$;

revoke all on function public.get_public_business(text) from public;
grant execute on function public.get_public_business(text) to anon, authenticated, service_role;

create or replace function public.get_public_services(p_business_id uuid)
returns table (
  id uuid,
  business_id uuid,
  name text,
  description text,
  duration_minutes integer,
  price_cents integer
)
language sql
security definer
set search_path = ''
as $$
  select s.id, s.business_id, s.name, s.description, s.duration_minutes, s.price_cents
  from public.services s
  join public.businesses b on b.id = s.business_id
  where s.business_id = p_business_id
    and s.is_active = true
    and b.is_active = true
  order by s.created_at asc
$$;

revoke all on function public.get_public_services(uuid) from public;
grant execute on function public.get_public_services(uuid) to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Restore the booking RPC's security posture and serialize it with service
-- deletion. The service lock is the shared mutex for the delete/create race;
-- the booking exclusion constraint remains the final interval guard.
-- ---------------------------------------------------------------------------
create or replace function public.create_booking(
  p_business_id uuid,
  p_service_id uuid,
  p_start_at timestamptz,
  p_customer_name text,
  p_customer_phone text,
  p_customer_email text default null,
  p_customer_note text default null
)
returns public.bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_business public.businesses;
  v_service public.services;
  v_customer public.customers;
  v_booking public.bookings;
begin
  select * into v_business
  from public.businesses
  where id = p_business_id
  for update;

  if v_business is null then
    raise exception 'BUSINESS_NOT_FOUND';
  end if;
  if not v_business.is_active then
    raise exception 'BUSINESS_INACTIVE';
  end if;
  if p_start_at < now() + make_interval(mins => v_business.min_notice_minutes) then
    raise exception 'BOOKING_BEFORE_MIN_NOTICE';
  end if;

  select * into v_service
  from public.services
  where id = p_service_id
    and business_id = p_business_id
  for update;

  if v_service is null then
    raise exception 'SERVICE_NOT_FOUND';
  end if;
  if not v_service.is_active then
    raise exception 'SERVICE_INACTIVE';
  end if;

  insert into public.customers (business_id, name, phone, email)
  values (p_business_id, p_customer_name, p_customer_phone, p_customer_email)
  on conflict (business_id, phone)
  do update set
    name = excluded.name,
    email = coalesce(excluded.email, public.customers.email)
  returning * into v_customer;

  insert into public.bookings (
    business_id, service_id, customer_id, customer_name_snapshot,
    customer_phone_snapshot, customer_email_snapshot, service_name_snapshot,
    duration_minutes_snapshot, price_cents_snapshot, start_at, end_at,
    customer_note
  )
  values (
    p_business_id, v_service.id, v_customer.id, p_customer_name,
    p_customer_phone, p_customer_email, v_service.name,
    v_service.duration_minutes, v_service.price_cents, p_start_at,
    p_start_at + make_interval(mins => v_service.duration_minutes),
    p_customer_note
  )
  returning * into v_booking;

  return v_booking;
end;
$$;

revoke all on function public.create_booking(uuid, uuid, timestamptz, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.create_booking(uuid, uuid, timestamptz, text, text, text, text)
  to service_role;

create or replace function public.delete_service_if_unused(
  p_business_id uuid,
  p_service_id uuid,
  p_now timestamptz default now()
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_service public.services;
begin
  -- Match create_booking's lock order (business, then service).
  perform 1
  from public.businesses
  where id = p_business_id
  for update;

  select * into v_service
  from public.services
  where id = p_service_id
    and business_id = p_business_id
  for update;

  if v_service is null then
    return 'NOT_FOUND';
  end if;

  if exists (
    select 1
    from public.bookings b
    where b.business_id = p_business_id
      and b.service_id = p_service_id
      and b.status = 'confirmed'
      and b.end_at > p_now
  ) then
    return 'HAS_SCHEDULED_BOOKINGS';
  end if;

  delete from public.services
  where id = p_service_id
    and business_id = p_business_id;
  return 'DELETED';
end;
$$;

revoke all on function public.delete_service_if_unused(uuid, uuid, timestamptz)
  from public, anon, authenticated;
grant execute on function public.delete_service_if_unused(uuid, uuid, timestamptz)
  to service_role;

-- ---------------------------------------------------------------------------
-- Reminder claims: candidates are leased atomically with SKIP LOCKED. A stale
-- worker cannot mark a newer claim because the token is fenced in the update.
-- ---------------------------------------------------------------------------
alter table public.bookings
  add column if not exists reminder_claimed_at timestamptz,
  add column if not exists reminder_claim_token uuid;

drop function if exists public.get_due_booking_reminders(integer);

create or replace function public.get_due_booking_reminders(
  p_lead_minutes integer default 1440
)
returns table (
  id uuid,
  business_id uuid,
  business_name text,
  business_slug text,
  customer_name_snapshot text,
  customer_email_snapshot text,
  service_name_snapshot text,
  start_at timestamptz,
  public_code text,
  reminder_claim_token uuid
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  with candidates as (
    select b.id
    from public.bookings b
    join public.businesses bus on bus.id = b.business_id
    where bus.plan = 'pro'
      and b.status = 'confirmed'
      and b.reminder_sent_at is null
      and b.customer_email_snapshot is not null
      and b.customer_email_snapshot <> ''
      and b.start_at > now()
      and b.start_at <= now() + make_interval(mins => greatest(1, least(p_lead_minutes, 1440)))
      and (
        b.reminder_claimed_at is null
        or b.reminder_claimed_at < now() - interval '15 minutes'
      )
    order by b.start_at asc
    limit 50
    for update of b skip locked
  ), claimed as (
    update public.bookings b
    set reminder_claimed_at = now(),
        reminder_claim_token = extensions.gen_random_uuid()
    from candidates c
    where b.id = c.id
    returning b.*
  )
  select
    b.id,
    b.business_id,
    bus.name,
    bus.slug,
    b.customer_name_snapshot,
    b.customer_email_snapshot,
    b.service_name_snapshot,
    b.start_at,
    b.public_code,
    b.reminder_claim_token
  from claimed b
  join public.businesses bus on bus.id = b.business_id
  order by b.start_at asc;
end;
$$;

revoke all on function public.get_due_booking_reminders(integer)
  from public, anon, authenticated;
grant execute on function public.get_due_booking_reminders(integer) to service_role;

create or replace function public.set_booking_reminders_sent(
  p_booking_ids uuid[],
  p_claim_tokens uuid[]
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  update public.bookings b
  set reminder_sent_at = now(),
      reminder_claimed_at = null,
      reminder_claim_token = null
  from unnest(p_booking_ids, p_claim_tokens) as claimed(id, claim_token)
  where b.id = claimed.id
    and b.reminder_claim_token = claimed.claim_token
    and b.status = 'confirmed'
    and b.reminder_sent_at is null;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.set_booking_reminders_sent(uuid[], uuid[])
  from public, anon, authenticated;
grant execute on function public.set_booking_reminders_sent(uuid[], uuid[])
  to service_role;

-- Keep the old batch signature for operators/scripts already using it. It is
-- idempotent but cannot fence a worker; new senders must use the two-array form.
create or replace function public.set_booking_reminders_sent(p_booking_ids uuid[])
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  update public.bookings
  set reminder_sent_at = now(),
      reminder_claimed_at = null,
      reminder_claim_token = null
  where id = any(p_booking_ids)
    and status = 'confirmed'
    and reminder_sent_at is null;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.set_booking_reminders_sent(uuid[])
  from public, anon, authenticated;
grant execute on function public.set_booking_reminders_sent(uuid[])
  to service_role;
